### ISSUE TITLE
🐛 [bug]: Can't pass -ignore flag

### ISSUE THREAD

**Issue by joernott** [raven-actions/actionlint#13]
### 🐛 What happened?

In one of my workflows, I am using an action with dynamic outputs. Actionlint reports those (as they are not explicitly declared) with the error message
```shell
property "deprecated_tests_failure_pattern" is not defined in object type {conclusion: string; outcome: string; outputs: {string => string}} [expression]
```
I would like to ignore them. Locally, I use 
```shell
 actionlint -ignore 'property ".+" is not defined in object type'
```
to achieve this. I tried passing the string to the "flags" input of your action, using
```yaml
      - name: Run actionlint
        id: actionlint
        uses: raven-actions/actionlint@v1
        with:
          flags: '-ignore "property \".+\" is not defined in object type"'
```
but I am getting an error "could not read "type\"": open type": no such file or directory"

I am no javascript expert, but I assume this is due to https://github.com/raven-actions/actionlint/blob/main/action.yml#L355 splitting the "flags" at every space, completely ignoring the quotes.

### 🔬 How to reproduce?

Use an action with dynamic output (e.g. https://github.com/joernott/load_testplan/tree/main) and run actionlint on it

### 🌌 Environment (actionlint action)

v1.0.2

### 🌌 Environment (actionlint)

1.6.26

### 🌌 Environment (GitHub Runner OS)

Linux

### 📈 Expected behavior

There should be a way to pass multiple ignore patterns to the action, e.g. with a dedicated "input" input.

### 📜 Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
