### ISSUE TITLE
🐛 [bug]: using v1 gives node16 deprecation warnings

### ISSUE THREAD

**Issue by joernott** [raven-actions/actionlint#21]
### 🐛 What happened?

We start seeing deprecation warnings aboud node16 when using raven-actions/actionlint@v1:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

### 🔬 How to reproduce?

Call actionlint action

### 🏗️ Code Sample / Log

```Shell
[...]
  actionlint:
    needs: ['init', 'begin_report_phase']
    if: ${{ always() && needs.init.outputs.actionlint_skip != 'true' }}
    runs-on: ${{ fromJSON(inputs.runs_on) }}
    steps:
      - name: Install npm on private runner
        if: ${{ inputs.runs_on != '"ubuntu-latest"'}}
        run: |
          NPM=$(type -p 'npm'||true)
          if [ -z "${NPM}" ]; then
            echo -e "\033[0;35m###  Installing npm ###\033[0m"
            sudo DEBIAN_FRONTEND=noninteractive apt-get -qq update
            sudo apt-get -qq install npm
          fi

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run actionlint
        id: actionlint
        uses: raven-actions/actionlint@v1
```

### 🌌 Environment (actionlint action)

1.0.3

### 🌌 Environment (actionlint)

1.6.26-Linux-X64

### 🌌 Environment (GitHub Runner OS)

Linux

### 📈 Expected behavior

actions/cache is upgraded to v4 to remove the warning

### 📜 Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by mvanduijker** [comment]
It should be fixed with this https://github.com/raven-actions/actionlint/pull/20 
We have to wait for a new release.

**Comment by DariuszPorowski** [comment]
Will review, bump deps, test and release new one around end of 1st week of March.

**Comment by mvanduijker** [comment]
any way I can help to get this released?

**Comment by pakosak** [comment]
any update on the release @DariuszPorowski ?

**Comment by DariuszPorowski** [comment]
@mvanduijker @pakosak currently this PR is a blocker: https://github.com/raven-actions/actionlint/pull/22 
After will solve it, then breaking change (v2 release) will happen with switch to node20

**Comment by kxc171** [comment]
@DariuszPorowski - Any plans to still cutover a `v2` tag for this yet (or update the existing `v1` tag)? This would be really nice to address since at this point GH has started forcing Node20 on older versions anyways.

**Comment by DariuszPorowski** [comment]
@kxc171 done :) v2 released :)

**Comment by kxc171** [comment]
Chiming in, while I do like the idea of leaning into immutable versions, there are benefits to having "fuzzy" versions available for fixes and security issues. While it does open the possibility for someone malicious to update a `vX` tag (since they are NOT immutable), this can be prevented by pinning to full commit SHA's, which is a common practice and something a lot of tooling (eg: Renovate) support updating.

This gives the best of both worlds by allowing users to pin to a known version (SHA) or continue to use a `vX` tag to continue getting updates.

Below is an example Workflow that could be used to easily create `vX` and `vX.Y` tags from a full `vX.Y.Z` version, which can easily be made at your own cadence using the GitHub Releases page (or just pushing it yourself haha). This won't work if you use branch/tag protection rules (you'd need to use your own PAT).

<details>
<summary>release.yaml</summary>

```yaml
name: Release Action

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  release:
    name: Release action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all tags

      - name: Push version tags
        id: tags
        run: |
          MAJOR=$(echo "$GITHUB_REF_NAME" | cut -d . -f 1)
          MINOR=$(echo "$GITHUB_REF_NAME" | cut -d . -f 2)
          PATCH=$(echo "$GITHUB_REF_NAME" | cut -d . -f 3)

          git tag -f "$MAJOR" "$GITHUB_SHA"
          git tag -f "$MAJOR.$MINOR" "$GITHUB_SHA"
          git tag -f "$MAJOR.$MINOR.$PATCH" "$GITHUB_SHA"
          git push -f -u origin "$MAJOR"
          git push -f -u origin "$MAJOR.$MINOR"
          git push -f -u origin "$MAJOR.$MINOR.$PATCH"

          git show-ref --tags | grep "$GITHUB_SHA"
```

</details>
