### ISSUE TITLE
❓ [question]: How to use a custom configuration file (path)?

### ISSUE THREAD

**Issue by lermontex** [raven-actions/actionlint#29]
### ✅ Checklist

- [x] I've searched the project's [`issues`](https://github.com/raven-actions/actionlint/issues?q=is%3Aissue) and did not find answer for my question.

### ❓ Question

I'm currently using this configuration of Github Actions:

```
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        uses: raven-actions/actionlint@v2
        with:
          flags: -ignore SC2129
```

I would like to put the rules for ignoring errors in a separate configuration file

I have read the `rhysd/actionlint` documentation

https://github.com/rhysd/actionlint/blob/main/docs/config.md#configuration-file

My understanding is that the configuration file should be placed in the `.github` directory, but what if I want to place it in the root directory of the project? Is that possible?

Unfortunately I haven't found a way to specify a custom path to the config file

### 📎 Additional context

It would be great if there was a way to specify a custom path for the configuration file. What do you think about it? 

```
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        uses: raven-actions/actionlint@v2
        with:
          config-file: .actionlint.yaml
```

_No response_

### 📜 Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by lermontex** [comment]
Solved with config-file flag:

```
      - name: Actionlint
        uses: raven-actions/actionlint@v2
        with:
          flags: -config-file .actionlint.yaml
```
